import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "../context/AuthContext";
import QueryProvider from "@/components/providers/QueryProvider";
import ProfileGuard from "@/components/ProfileGuard";

// Google Fonts
const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "SoSign",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${beVietnamPro.variable} antialiased`}>
        <AuthProvider>
          <QueryProvider>
            <ProfileGuard>
              <Navbar />
              <main>{children}</main>
            </ProfileGuard>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
